version: '3.8'
services:
  postgres:
    image: postgres:alpine
    container_name: mentor_db
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mentor_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: mentor_app
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/mentor_db
      - NODE_ENV=production
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
